application: to-uri-st
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /import
  script: import.py
  login: admin

- url: /_
  static_dir: public

- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /.*
  script: dispatch.py
  
